### PR TITLE
Fixes generated source maps root paths

### PR DESCRIPTION
**Pull request by arcanis**
This PR fixes the root path generated in the source map.

Assuming `cjsify manifest.js`, the following code which was generated :

```
{ ..., "sourceRoot" : "/home/arcanis/project/" }
```

Will become (with `--source-map-file project.map.js`)

```
{ ..., "sourceRoot" : "." }
```

Or, with `--source-map-file misc/project.map.js`

```
{ ..., "sourceRoot" : ".." }
```

**Note** : I have also fixed the Makefile since the last version of coffeescript does not seem to have the `--js` option. I assumed that it was the equivalent of `--print`, except that it reads from the file specified as the first argument instead of the standard input.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Thanks, @arcanis. I've pushed f6b2efd6 to fix this issue in a very similar manner. I didn't need nor want the other changes. I'm not sure in what way you initialised the working directory for development, but you somehow installed the old CoffeeScript compiler.

**Comment by arcanis** [comment]
Ok, np :)

I don't know, I installed CoffeeScript using `npm install coffee-script`. Weird.

**Comment by arcanis** [comment]
However, iirc, `path.relative` does return an empty string instead of `.`, which means that the `sourceRoot` will be omitted by escodegen.

When I tried such generated source map on chrome, it broke by not being able to find the original source files (hence the `|| '.'` in my commits, which forced the `sourceRoot` to use the correct relative path).

**Comment by michaelficarra** [comment]
I figured that `sourceMapFile` was always a file, and `root` was always a directory, so there's no way they could ever actually be the same.

**edit:** Also, just use `npm install`, and all the dependencies are fetched for you automatically.

**Comment by arcanis** [comment]
Right, but `path.dirname` (which is called before `path.relative`) will return the directory of `sourceMapFile`. So for example, with the following options, you will not have `sourceRoot` parameter

```
cjsify --source-map-file ./foo.js -r ./
```

**Comment by michaelficarra** [comment]
Ah, right. Thanks for the catch.

**Pull request closed without merging**
