### PR TITLE
Travis CI Settings

### PR DESCRIPTION
**Pull request by fulmicoton**
I just added Travis CI settings. Things can be a little tricky with submodules.
I ran it on Travis CI on my branch, and checked the log to see that it went through the whole install and ran the 6 unit tests.

Everything was ok :
https://travis-ci.org/poulejapon/commonjs-everywhere/jobs/5270929

### CODE REVIEW

**Comment by michaelficarra** [comment]
Awesome, thanks.

**Comment by fulmicoton** [comment]
Hmmm... That seems even weirder than that.

I also tried it on my forked repo. The travis conf files asks to test it on node v0.8, and node v0.10. Travis CI does not offer node v0.10 as it does not even exist (or does it?) and fall backs on node v0.8. Long story short on my branch it worked for the first 0.8 (https://travis-ci.org/poulejapon/commonjs-everywhere/jobs/5277565), and worked for the 0.10->0.8 one (https://travis-ci.org/poulejapon/commonjs-everywhere/jobs/5277566).

While on your repo, it failed for both !

**Comment by fulmicoton** [comment]
Run the test on both 0.8 and 0.9.
Now 0.8 is failing but 0.9 is working.
https://travis-ci.org/poulejapon/commonjs-everywhere

**Comment by michaelficarra** [comment]
Wow, very weird. You don't think out could be a race condition, do you? I am relying on `_setup.coffee` being executed before any other test. Maybe if we `require` it from the other tests, it will behave more deterministically? I doubt that is the problem, though, since CoffeeScriptRedux uses the same setup strategy.

**Comment by fulmicoton** [comment]
(Sorry for the delay.) I don't have the slightest idea of what happened ... How unlikely could it be, race conditions would explain that. What about we wait and see if it happens again?

**Comment by michaelficarra** [comment]
No problem. I got everything resolved. It was a platform inconsistency. Linux doesn't guarantee a file ordering when listing a directory. Neither does Mocha. So I needed to list the tests in order by globbing with `*`. Problem solved.

**Comment by fulmicoton** [comment]
Nice catch !

**Pull request merged**
